language: node_js
sudo: required
services:
  - mongodb
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
 - chmod +x ./test.sh
script: ./test.sh
