call meteor add reactive-var
call meteor add jquery
call meteor add mrt:bootstrap-3
call meteor add accounts-base
call meteor add accounts-password
call meteor add ian:accounts-ui-bootstrap-3
call meteor add mquandalle:jade
call meteor add iron:router
call meteor add alanning:roles
call meteor add dburles:mongo-collection-instances
call meteor add mizzao:jquery-ui
call meteor add dsyko:meteor-node-csv
call meteor add nimble:restivus
call meteor add email
call meteor add mystor:device-detection
call meteor remove autopublish
call meteor remove insecure