Template.model_instance_name_phone.events
    'click': (evt, template) ->
        console.log 'list details item clicked ', template.data.name
        #Session.set(Current_Model_Id,template.data._id);
        modelDefId = Session.get(Current_Model_Id)
        MobileRouteHelpers.showModelDetails modelDefId, template.data._id
        return

Template.model_instance_name_phone.helpers
    name: ->
        if @['name']
            @name
        else
            @[ModelHelpers.currentModel()[MDF_SummaryPropertyName]]

# ---
# generated by js2coffee 2.1.0