Template.model_def_name_phone.events 'click': (evt, template) ->
    console.log 'list details item clicked ', template.data.name
    Session.set Current_Model_Id, template.data._id
    MobileRouteHelpers.showModelInstanceList template.data._id
    return
Template.model_def_name_phone.helpers name: ->
    if @['name']
        @name
    else
        @[ModelDefHelpers.currentModel()[MDF_SummaryPropertyName]]

# ---
# generated by js2coffee 2.1.0