Template.button_add_model_phone.events
  'click': (evt, template) ->
    Session.set Editing_Model, false
    Session.set Add_Model, true
    EventUtils.stopDefault evt
    currentModel = ModelDefHelpers.currentModel()
    console.log 'this is phone'
    MobileRouteHelpers.showNewModelInstanceForm currentModel._id
    return

# ---
# generated by js2coffee 2.1.0