Router.route '/mobile/modeldefs/', (->
  @render 'model_def_list_phone', {}
  return
), name: 'model_def_list_phone'


Router.route '/mobile/models/:_id', (->
  model = ModelDefDb.findOne _id:@params._id
  if !ArrayUtils.contains(AllReady_Published_Models,model.name)
    MongoUtils.createModelIfNotExists model.name

  @subscribe(model.name).wait()

  @render 'model_instance_list_phone', data: ModelDefDb.findOne(_id: @params._id)
  return
), name: 'model_instance_list_phone'


Router.route '/mobile/models/:_id/details/:itemId', (->
  model = ModelDefDb.findOne _id:@params._id
  if !ArrayUtils.contains(AllReady_Published_Models,model.name)
    MongoUtils.createModelIfNotExists model.name

  @subscribe(model.name).wait()
  @render 'model_instance_details_phone', data: ModelHelpers.getModelInstanceById(@params.itemId)
  return
), name: 'model_instance_details_phone'

Router.route '/mobile/models/:_id/:' + Form_Mode, (->
  if @params[Form_Mode] == Form_Mode_New
    @render 'model_form_phone'
  else
    @render 'model_form_phone', data: ModelHelpers.getCurrentEditingModelData()
  return
), name: 'model_instance_form_mobile'

# ---
# generated by js2coffee 2.1.0